### ISSUE TITLE
fio_plot: ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by jodykpw** [louwrentius/fio-plot#27] opened 2020-08-03 01:44 UTC
`./bench_fio -d /data -t directory -s 1g --mode randread -o /data/benchmarks --iodepth 1 2 4 8 16 32 64 --numjobs 1  --block-size 16k`

`./fio_plot/fio_plot -i /data/benchmarks/data/16k -T "Apple SSD AP0256M BLOCK_SIZE 16K On Vagrant" -s https://louwrentius.com -l -n 1 -r randread`

Traceback (most recent call last):
  File "/app/fio_plot/fio_plot", line 151, in <module>
    main()
  File "/app/fio_plot/fio_plot", line 139, in main
    uses_json_files[item](settings, parsed_data)
  File "/app/fio_plot/fiolib/bar2d.py", line 14, in chart_2dbarchart_jsonlogdata
    data = shared.get_record_set(settings, dataset, dataset_types,
  File "/app/fio_plot/fiolib/shared_chart.py", line 99, in get_record_set
    lat_stddev_percent = supporting.raw_stddev_to_percent(
  File "/app/fio_plot/fiolib/supporting.py", line 222, in raw_stddev_to_percent
    percent = round((int(y) / int(x)) * 100, 0)
**ZeroDivisionError: division by zero**

**Comment by louwrentius** [comment] 2020-08-03 10:38
Can you share the benchmark data in a compressed file?

**Comment by louwrentius** [comment] 2020-08-03 14:34
I have committed a possible fix to the master branch. Can you verify the issue is solved?

**Comment by jodykpw** [comment] 2020-08-03 15:01
Sorry, I don't have those benchmark data anymore, just tried again is fine now.

**Comment by louwrentius** [comment] 2020-08-03 16:07
Thanks for the feedback.

**Closed by louwrentius** 2020-08-03 16:07 UTC
