### ISSUE TITLE
bench-fio can create empty csv files, to which fio-plot reacts with an unhelpful message

### ISSUE THREAD

**Issue by vbrik** [louwrentius/fio-plot#68] opened 2022-01-04 18:52 UTC
When doing some quick tests on NVMe, I ran into the situation where bench-fio created empty csv files, apparently because --loginterval was too close to the duration of an individual benchmark trial.

When that happened, fio-plot threw an exception with the error message "statistics.StatisticsError: mean requires at least one data point" (in parse_raw_cvs_data of dataimport.py), which was not very helpful.

Perhaps it would be good to print a more helpful error message on this exception, or implement some sanity checking to avoid this situation?

**Comment by louwrentius** [comment] 2022-02-03 00:02
Thanks for the feedback. The issue is resolved in the master branch, I believe.

**Closed** 2022-02-20 22:03 UTC
